
list:
    just -l


download-repo: vibecoding-copy

# download a copy of a git repository so we can play with it.
vibecoding-copy:
    git clone https://github.com/palladius/vibecoding vibecoding-copy
